title: My first blog
author: Ãlvaro Ortiz
email: alvrtmoya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog via GitHub, I hope it is valid for future purposes!

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  alvart-98 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
